### ISSUE TITLE
TODO: add aliases to apache sites provisioner

### ISSUE THREAD

**Issue by jeanlescure** [vagrant-easy/VagrantEasy-LAMP#1]
The `development.yml` contains a sub-section under `sites` called `alias` for setting up the `ServerAlias` config for each vhost under apache:

```
sites:
  - site_name: 'VagrantEasy-LAMP-example-app'
    local_path: '../VagrantEasy-LAMP-example-app' # Relative to Vagrantfile location
    remote_path: '/var/www/VagrantEasy-LAMP-example-app'
    enabled: true
    log_level: debug
    host: 'example.dev'
    aliases: #<= THIS ONE RIGHT HERE
      - 'www.example.dev'
      - 'ww2.example.dev'
```

Let's make sure to update the `scripts/provisions/50.sites.rb` and `scripts/provisions/50.sites.sh` in order to make this functionality available; hopefully sooner than later.

:+1:
